version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka:1:1"
  kafdrop:
    image: dockerproxy.com/obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    depends_on:
      - zookeeper
      - kafka
  data-generator:
    image: cute/datagen
    build: ./cutedatagen
    depends_on:
      - kafka

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password --secure_file_priv=/data
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: "sql-demo"
      MYSQL_PASSWORD: "demo-sql"
      MYSQL_DATABASE: "sql-demo"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/mysql-spend-report-init:/docker-entrypoint-initdb.d
      - ./data:/data


  grafana:
    image: grafana/grafana:7.5.8
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./docker/grafana-spend-report-init/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana-spend-report-init/dashboard.json:/etc/grafana/dashboard.json
      - ./docker/grafana-spend-report-init/grafana.ini:/etc/grafana/grafana.ini